<a href="https://colab.research.google.com/github/jumbokh/encoding-BCH/blob/main/BCH_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive') # 點擊網址，選擇 Google 帳號登入，然後將授權碼貼回輸入框中

Mounted at /content/gdrive


In [2]:
!ln -fs /content/gdrive/My\ Drive/Colab\ Notebooks/BCH/ /app
%cd /app

/content/gdrive/My Drive/Colab Notebooks/BCH


In [3]:
!ls # 確定目錄有訓練資料

BCH	  BCH_R_S_Input_Model.png  extract_parameters.py
BCH.csv   BCH_Train.ipynb	   Final-model.h5
BCH-logs  data			   test.h5


In [4]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow import keras
from tensorflow.keras import layers

In [5]:
data = pd.read_table("data/Training_one_to_50000.txt",sep=',',header=None)
print(data.shape)
data.head()

(50000, 75)


0         1         2         3         4   ...  70  71  72  73  74
0  2.236141  0.677073  1.892023  2.212047  2.173484  ...   0   0   0   1   0
1  2.727983  1.644212  1.913891  1.740416  2.590680  ...   1   0   1   0   1
2  2.409236  2.801631  2.057426  2.184759  2.683636  ...   0   0   0   1   1
3  1.791774  1.749787  2.585813 -0.052639  2.278452  ...   0   1   0   1   1
4  2.095124  3.361770  2.132792  1.169481  1.952437  ...   1   1   0   0   0

[5 rows x 75 columns]

In [25]:
from sklearn import preprocessing   
import numpy as np    

In [28]:
#　https://aifreeblog.herokuapp.com/posts/54/data_science_203/
Min_Max_Scaler = preprocessing.MinMaxScaler( feature_range=(-1,1) ) # 設定縮放的區間上下限

In [32]:
c = np.array(data)
data_recp = c[:,:63]
MinMax_Data = Min_Max_Scaler.fit_transform( data_recp ) # Data 為原始資料

In [33]:
print(MinMax_Data.shape)
print(MinMax_Data[:5])

(50000, 63)
[[ 0.16526226 -0.38988075 -0.02269398  0.16133774  0.14035665 -0.18627233
   0.48127444  0.26965293  0.05198578 -0.1236961   0.19623933 -0.0816841
  -0.08163587 -0.05482516  0.09061733  0.36265302  0.29256801  0.03144075
  -0.48678055 -0.70714107 -0.04431095  0.14307799 -0.38513189 -0.35302213
   0.33823341  0.04047587  0.31357988 -0.3435214   0.33521773 -0.32394972
  -0.13782901 -0.21811168 -0.08205822 -0.12338132  0.42959645  0.21186972
   0.00567064  0.34281986  0.09391528  0.09841882  0.4096713   0.07219989
  -0.17104073  0.06078598 -0.03253457 -0.24751141  0.10577498  0.14099224
   0.09357883 -0.02285654 -0.08320669 -0.16946341 -0.13845678  0.29875817
   0.08114705 -0.02890881  0.06404679  0.10598091 -0.13500534 -0.04734413
  -0.09816704  0.11109946  0.04287932]
 [ 0.32877798 -0.10020427 -0.0155947   0.00954863  0.27957178  0.13046238
  -0.1312923   0.48681309 -0.12357932 -0.04081672  0.47005905 -0.52517876
   0.19627347  0.29465622 -0.36664966  0.17343864  0.37194958 

In [34]:
np.array(MinMax_Data).mean()

0.04495322885969454

In [42]:
b = np.array(data)
data_syndrom = b[:,63:len(b[0])]
print(data_syndrom.shape)
print(data_syndrom[:5])

(50000, 12)
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0.]]


# Data 最大值 最小值

In [43]:
print(MinMax_Data.max())
print(MinMax_Data.min())

1.0000000000000002
-1.0


In [ ]:
pd.DataFrame(data_syndrom).dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
dtype: object

In [44]:
datasets = pd.read_table("data/Validation_one_to_50000.txt",sep=',',header=None)
print(datasets.shape)
print(datasets.head())

(50000, 63)
   0   1   2   3   4   5   6   7   8   ...  54  55  56  57  58  59  60  61  62
0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
2   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
3   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0

[5 rows x 63 columns]


In [ ]:
data_num = datasets.shape[0]
# 取得一筆與data數量相同的亂數索引，主要目的是用於打散資料
indexes = np.random.permutation(data_num)
# 並將亂數索引值分為Train、val和test分為，這裡的劃分比例為6:2:2
train_indexes = indexes[:int(data_num *0.6)]
val_indexes = indexes[int(data_num *0.6):int(data_num *0.8)]
test_indexes = indexes[int(data_num *0.8):]
# 透過索引值從data取出訓練資料、驗證資料和測試資料
x_train = datasets.loc[train_indexes]
x_val = datasets.loc[val_indexes]
x_test = datasets.loc[test_indexes]

In [ ]:
print(x_train.shape)
print(x_val.shape)
print(x_test.shape)

(30000, 63)
(10000, 63)
(10000, 63)


In [ ]:
syndrom = pd.DataFrame(data_syndrom)
x_train1 = syndrom.loc[train_indexes]
x_val1 = syndrom.loc[val_indexes]
x_test1 = syndrom.loc[test_indexes]

In [ ]:
print(x_train1.shape)
print(x_val1.shape)
print(x_test1.shape)

(30000, 12)
(10000, 12)
(10000, 12)
