<a href="https://colab.research.google.com/github/jumbokh/encoding-BCH/blob/main/BCH_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive') # 點擊網址，選擇 Google 帳號登入，然後將授權碼貼回輸入框中

Mounted at /content/gdrive


In [2]:
!ln -fs /content/gdrive/My\ Drive/Colab\ Notebooks/BCH/ /app
%cd /app

/content/gdrive/My Drive/Colab Notebooks/BCH


In [3]:
!ls # 確定目錄有訓練資料

BCH  BCH-logs  BCH_Train.ipynb	data  Final-model.h5


In [4]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow import keras
from tensorflow.keras import layers

In [5]:
data = pd.read_table("data/Training_one_to_50000.txt",sep=',',header=None)
print(data.shape)
data.head()

0         1         2         3         4   ...  70  71  72  73  74
0  2.236141  0.677073  1.892023  2.212047  2.173484  ...   0   0   0   1   0
1  2.727983  1.644212  1.913891  1.740416  2.590680  ...   1   0   1   0   1
2  2.409236  2.801631  2.057426  2.184759  2.683636  ...   0   0   0   1   1
3  1.791774  1.749787  2.585813 -0.052639  2.278452  ...   0   1   0   1   1
4  2.095124  3.361770  2.132792  1.169481  1.952437  ...   1   1   0   0   0

[5 rows x 75 columns]

In [7]:
b = np.array(data)
data_syndrom = b[:,63:len(b[0])]
print(data_syndrom.shape)
print(data_syndrom[:5])

(50000, 12)
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0.]]


# Data 最大值 最小值

In [20]:
print(b.max())
print(b.min())

5.4348508251866985
-1.7403611927561329


In [10]:
pd.DataFrame(data_syndrom).dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
dtype: object

In [ ]:
dat = np.array(data)


In [12]:
datasets = pd.read_table("data/Validation_one_to_50000.txt",sep=',',header=None)
print(datasets.shape)
print(datasets.head())

(50000, 63)
   0   1   2   3   4   5   6   7   8   ...  54  55  56  57  58  59  60  61  62
0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
2   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
3   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0

[5 rows x 63 columns]


In [14]:
data_num = datasets.shape[0]
# 取得一筆與data數量相同的亂數索引，主要目的是用於打散資料
indexes = np.random.permutation(data_num)
# 並將亂數索引值分為Train、val和test分為，這裡的劃分比例為6:2:2
train_indexes = indexes[:int(data_num *0.6)]
val_indexes = indexes[int(data_num *0.6):int(data_num *0.8)]
test_indexes = indexes[int(data_num *0.8):]
# 透過索引值從data取出訓練資料、驗證資料和測試資料
x_train = datasets.loc[train_indexes]
x_val = datasets.loc[val_indexes]
x_test = datasets.loc[test_indexes]

In [15]:
print(x_train.shape)
print(x_val.shape)
print(x_test.shape)

(30000, 63)
(10000, 63)
(10000, 63)


In [17]:
syndrom = pd.DataFrame(data_syndrom)
x_train1 = syndrom.loc[train_indexes]
x_val1 = syndrom.loc[val_indexes]
x_test1 = syndrom.loc[test_indexes]

In [18]:
print(x_train1.shape)
print(x_val1.shape)
print(x_test1.shape)

(30000, 12)
(10000, 12)
(10000, 12)
