<a href="https://colab.research.google.com/github/jumbokh/encoding-BCH/blob/main/my_entropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import plot_model
from tensorflow.keras.layers import LeakyReLU
from IPython.display import Image

In [2]:
from keras import backend as K
num_classes=7

In [3]:
def mycrossentropy(y_true, y_pred, e=0.1):
    return (1-e)*keras.losses.binary_crossentropy(y_pred,y_true) + e*keras.losses.binary_crossentropy(y_pred, K.ones_like(y_pred)/num_classes)

In [16]:
X = np.zeros([7,7])
print(X)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
y = X.copy()
for i in range(7):
  for j in range(7):
    a = np.random.random_integers(6)
    if a > 4:
      y[i][j]=1
print(y)

[[1. 1. 0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1. 0. 1.]
 [1. 0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  after removing the cwd from sys.path.


In [21]:
A=mycrossentropy(X,y)
print((A/2))

tf.Tensor(
[4.02531596 2.01651174 3.02091385 4.02531596 4.02531596 3.02091385
 1.01210964], shape=(7,), dtype=float64)


In [24]:
z = y.copy()
B=mycrossentropy(y,z)
print((B))

tf.Tensor(
[0.11780128 0.06660817 0.09220472 0.11780128 0.11780128 0.09220472
 0.04101161], shape=(7,), dtype=float64)


In [26]:
for i in range(7):
  a = z[i]
  b = y[i]
  ans=mycrossentropy(a,b)
  print("{}->{}=={}".format(a,b,ans)) 

[1. 1. 0. 0. 0. 1. 1.]->[1. 1. 0. 0. 0. 1. 1.]==0.11780127836720043
[1. 0. 0. 0. 1. 0. 0.]->[1. 0. 0. 0. 1. 0. 0.]==0.06660816734163015
[1. 0. 0. 0. 0. 1. 1.]->[1. 0. 0. 0. 0. 1. 1.]==0.09220472285441528
[1. 0. 0. 1. 1. 0. 1.]->[1. 0. 0. 1. 1. 0. 1.]==0.11780127836720043
[1. 0. 1. 1. 0. 0. 1.]->[1. 0. 1. 1. 0. 0. 1.]==0.11780127836720043
[1. 0. 0. 1. 1. 0. 0.]->[1. 0. 0. 1. 1. 0. 0.]==0.09220472285441528
[0. 0. 0. 0. 1. 0. 0.]->[0. 0. 0. 0. 1. 0. 0.]==0.041011611828844996


In [27]:
for i in range(7):
  a = X[i]
  b = y[i]
  ans=mycrossentropy(a,b)
  print("{}->{}=={}".format(a,b,ans)) 

[0. 0. 0. 0. 0. 0. 0.]->[1. 1. 0. 0. 0. 1. 1.]==8.050631920286365
[0. 0. 0. 0. 0. 0. 0.]->[1. 0. 0. 0. 1. 0. 0.]==4.033023488301213
[0. 0. 0. 0. 0. 0. 0.]->[1. 0. 0. 0. 0. 1. 1.]==6.041827704293788
[0. 0. 0. 0. 0. 0. 0.]->[1. 0. 0. 1. 1. 0. 1.]==8.050631920286365
[0. 0. 0. 0. 0. 0. 0.]->[1. 0. 1. 1. 0. 0. 1.]==8.050631920286365
[0. 0. 0. 0. 0. 0. 0.]->[1. 0. 0. 1. 1. 0. 0.]==6.041827704293788
[0. 0. 0. 0. 0. 0. 0.]->[0. 0. 0. 0. 1. 0. 0.]==2.024219272308636


In [44]:
g =[
[1.2308649660775985,1.312723718053264,-0.3006465808204184,2.3032949096024296,-0.19821281735170038,1.8118217397222234,2.5890258594232782],
[2.847115046702213,-0.5462487153926614,-0.33668348273485416,1.9386219955764177,2.2842563726621785,2.0476090971284573,2.7342782045170293],
[1.5648600109036637,-0.020715683962836184,0.30594147161762497,-0.21985215403092084,2.0489859724334174,1.3208733490230173,1.199750022587014],
[3.1620190151542733,1.8601399778526977,2.263777143193651,-0.08772031127301272,0.660756139912521,-0.21860940255514638,0.8335866856737455],
[2.0582424705666327,0.5775460325986279,2.280643052191872,0.8869852451963645,-0.18006662352942504,-0.005838434759084965,2.412993591568961],
[2.292389971655092,-0.19746479867533795,2.4250014817909102,-0.3392702411125943,2.5478402100785775,3.2460414914846565,2.472165469510512],
[3.818023219364495,2.1576506307139103,1.6305678118908196,1.7320189208083754,1.7320189208083754,1.5808812986176053,1.7320189208083754]   
]

In [47]:
from sklearn import preprocessing   
import numpy as np  

In [48]:
#　https://aifreeblog.herokuapp.com/posts/54/data_science_203/
Min_Max_Scaler = preprocessing.MinMaxScaler( feature_range=(-1,1) ) # 設定縮放的區間上下限

In [49]:
c = np.array(g)
Data = Min_Max_Scaler.fit_transform( c ) # Data 為原始資料

In [50]:
print(Data)

[[-1.          0.37503079 -0.97390224  1.         -1.          0.17208412
   0.84715842]
 [ 0.24944045 -1.         -1.          0.72400081  0.80802713  0.30819443
   1.        ]
 [-0.74180548 -0.61127767 -0.53461386 -0.90961957  0.63667545 -0.11132013
  -0.61470514]
 [ 0.49287663  0.77993955  0.88324205 -0.80961686 -0.3743974  -1.
  -1.        ]
 [-0.36039668 -0.16875992  0.89545627 -0.07192034 -0.9867838  -0.8771761
   0.66192871]
 [-0.1793892  -0.74201413  1.         -1.          1.          1.
   0.72419224]
 [ 1.          1.          0.42467466  0.56763527  0.40582263  0.03877173
  -0.05462593]]


In [45]:
yh = [
      
]

In [62]:
for i in range(7):
  a = yh[i]
  b = g[i]
  ans=mycrossentropy(a,b)
  print("{}->{}=={}".format(a,b,ans)) 

TypeError: ignored